/* Run with Node + Playwright, local server on RISKLAB_URL or port 8872.
   Screenshots are QA artifacts; assertions exercise the live numerical API. */
const { chromium } = require('playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const baseURL = process.env.RISKLAB_URL || 'http://127.0.0.1:8872';
const output = process.env.RISKLAB_QA_DIR || path.resolve(__dirname, '../results/browser');
fs.mkdirSync(output, { recursive:true });
const checks=[], browserErrors=[], consoleErrors=[];
const check = (name, passed=true) => { assert.ok(passed, name); checks.push({name,status:'passed'}); };
async function main(){
 const browser=await chromium.launch({channel:process.env.RISKLAB_BROWSER_CHANNEL || 'msedge',headless:true});
 try{
  const context=await browser.newContext({viewport:{width:1440,height:1100},reducedMotion:'reduce'});
  const page=await context.newPage();
  page.on('pageerror',error=>browserErrors.push(error.message));
  page.on('console',message=>{if(message.type()==='error'&&!message.text().includes('favicon'))consoleErrors.push(message.text());});
  const post=async(route,data)=>{const response=await context.request.post(`${baseURL}${route}`,{data});return {status:response.status(),body:await response.json()};};
  await page.goto(baseURL);
  await page.waitForFunction(()=>document.querySelector('#price-message').classList.contains('success'));
  check('Initial overview renders actual computed price curve',await page.locator('#hero-chart svg').count()===1);
  check('All six navigation sections exist',await page.locator('nav a').count()===6);
  check('Service connection is reported',await page.locator('#connection').innerText()==='本地数值内核已连接');
  await page.screenshot({path:path.join(output,'01-overview-desktop.png'),fullPage:true});
  await page.locator('nav a[data-page="pricing"]').focus();await page.keyboard.press('Enter');
  check('Keyboard Enter opens pricing section',await page.locator('#pricing').isVisible());
  await page.locator('#price-form input[name="spot"]').fill('110');
  check('Edited input marks old output stale',(await page.locator('#price-message').innerText()).includes('参数已更改'));
  let response=page.waitForResponse(r=>r.url().endsWith('/api/price')&&r.request().method()==='POST');
  await page.locator('#price-form button[type="submit"]').click();let result=await (await response).json();
  await page.waitForFunction(()=>document.querySelector('#price-message').classList.contains('success'));
  check('Spot update reaches real pricing API',result.parameters.spot===110);
  const initialPrice=result.bs;
  await page.locator('#price-form select[name="kind"]').selectOption('put');response=page.waitForResponse(r=>r.url().endsWith('/api/price')&&r.request().method()==='POST');await page.locator('#price-form button[type="submit"]').click();result=await(await response).json();
  await page.waitForFunction(()=>document.querySelector('#price-message').classList.contains('success'));
  check('Put calculation changes actual price and delta',result.bs<initialPrice&&result.greeks.delta<0);
  await page.screenshot({path:path.join(output,'02-pricing-desktop.png'),fullPage:true});
  await page.locator('#price-form input[name="spot"]').fill('-1');await page.locator('#price-form button[type="submit"]').click();
  check('Invalid spot blocked by accessible HTML validity',await page.locator('#price-form input[name="spot"]').evaluate(node=>!node.validity.valid));
  await page.locator('#price-form button[type="reset"]').click();
  await page.locator('nav a[data-page="hedging"]').click();
  async function runSimulation(){const pending=page.waitForResponse(r=>r.url().endsWith('/api/simulate')&&r.request().method()==='POST');await page.locator('#hedge-form button[type="submit"]').click();const reply=await pending;assert.equal(reply.status(),200);const body=await reply.json();await page.waitForFunction(()=>document.querySelector('#hedge-message').classList.contains('success'));return body;}
  let original=await runSimulation();
  check('Default simulation renders both strategy comparison and ledger',await page.locator('#hedge-results tbody tr').count()===6&&(await page.locator('#ledger tbody tr').count())===64);
  check('Histogram accounts for all simulated paths',original.histogram.counts.reduce((a,b)=>a+b,0)===original.parameters.n_paths);
  await page.locator('#hedge-form input[name="seed"]').fill('43');const changed=await runSimulation();
  check('Changing seed changes generated paths',JSON.stringify(changed.paths)!==JSON.stringify(original.paths));
  await page.locator('#hedge-form input[name="cost_bps"]').fill('0');const noFee=await runSimulation();
  check('Changing fee preserves paths and changes net performance',JSON.stringify(noFee.paths)===JSON.stringify(changed.paths)&&noFee.summary.mean_cost===0&&noFee.summary.mean_pnl>changed.summary.mean_pnl);
  await page.locator('#hedge-policy').selectOption('threshold');
  check('Threshold controls replace fixed interval controls',await page.locator('#threshold-field').isVisible()&&!(await page.locator('#every-field').isVisible()));
  const threshold=await runSimulation();check('Threshold policy is computed',threshold.parameters.policy.kind==='threshold');
  await page.locator('#path-model').selectOption('regime');await page.locator('#regime-fields input').fill('0.5');const regime=await runSimulation();
  check('Regime parameter reaches generated model',regime.parameters.model_parameters.vol2===.5);
  await page.locator('#path-model').selectOption('jump');const jump=await runSimulation();check('Jump diffusion scenario computes',jump.parameters.model==='jump'&&Number.isFinite(jump.summary.rmse));
  await page.screenshot({path:path.join(output,'03-hedging-desktop.png'),fullPage:false});
  await page.locator('#hedge-form details summary').click();await page.locator('#hedge-form input[name="n_paths"]').fill('3000');await page.locator('#hedge-form input[name="steps"]').fill('252');await page.locator('#hedge-form button[type="submit"]').click();
  check('Oversized simulation shows explicit client error',(await page.locator('#hedge-message').innerText()).includes('400,000'));
  const oversized=await post('/api/simulate',{n_paths:3000,steps:252});check('Server independently rejects oversized simulation',oversized.status===422);
  const downloadPromise=page.waitForEvent('download');await page.locator('#download-simulation').click();const download=await downloadPromise;
  check('Actual experiment JSON can be downloaded',download.suggestedFilename()==='risklab-seed-43.json');await download.saveAs(path.join(output,'sample-download.json'));
  await page.locator('nav a[data-page="historical"]').click();
  check('Executed historical evidence is rendered',await page.locator('#history-currency').count()===1&&await page.locator('#currency-evidence table').count()===2);
  await page.locator('#history-currency').selectOption('JPY');check('Currency switch updates evidence',await page.locator('#currency-evidence svg').getAttribute('aria-label')==='JPY 年度预测QLIKE');
  await page.screenshot({path:path.join(output,'04-historical-desktop.png'),fullPage:true});
  await page.locator('nav a[data-page="competencies"]').click();check('Capability union contains 18 dimensions',await page.locator('#competency-content tbody tr').count()===18);check('All 10 programs have official links',await page.locator('.program-item a').count()===10);
  check('External evidence boundaries remain visible',(await page.locator('#competency-content').innerText()).includes('需要外部证据'));
  await page.screenshot({path:path.join(output,'05-union-desktop.png'),fullPage:true});
  await page.locator('nav a[data-page="research-v2"]').focus();await page.keyboard.press('Enter');
  check('Keyboard opens V2 research and publication section',await page.locator('#research-v2').isVisible());
  await page.waitForFunction(()=>document.querySelectorAll('.v2-route').length===6);
  const research=await(await context.request.get(`${baseURL}/api/research-v2`)).json();
  check('V2 protocol displays actual six-currency scope',(await page.locator('#v2-protocol').innerText()).includes(research.protocol.data.historical.currencies.join(' · ')));
  check('V2 states retain all three independently loaded result artifacts',await page.locator('#v2-status article').count()===3);
  check('All three executed V2 artifacts are available within the API size bound',['historical','selection','convex'].every(key=>research[key].status==='available'));
  const mainComparison=research.selection.data.primary_comparison;
  check('V2 simulation primary interval uses the executed values',(await page.locator('#v2-primary .v2-interval-chart title').first().textContent()).includes(String(mainComparison.difference))&&(await page.locator('#v2-primary').innerText()).includes('区间包含 0'));
  check('V2 historical primary table includes all six currencies and both periods',await page.locator('#v2-primary .v2-result-block').nth(1).locator('tbody tr').count()===12);
  const originalSelection=await page.locator('#v2-selection-detail').innerText();
  await page.locator('#v2-scenario').selectOption('heston_shift');await page.locator('#v2-fee').selectOption('20');
  check('V2 distribution and fee selectors change actual risk-cost evidence',(await page.locator('#v2-selection-detail').innerText())!==originalSelection&&await page.locator('#v2-selection-detail table').first().locator('tbody tr').count()===3);
  await page.locator('#v2-scenario').selectOption('heston');await page.locator('#v2-fee').selectOption('5');
  check('V2 history selector includes all six actual currencies',await page.locator('#v2-currency option').count()===6);
  await page.locator('#v2-currency').selectOption('JPY');
  check('V2 historical currency changes the real annual chart',await page.locator('#v2-currency-detail svg').getAttribute('aria-label')==='JPY retrospective 年度净MSE');
  await page.locator('#v2-period').selectOption('additional_2026');
  const additional=research.historical.data.aggregate.find(row=>row.currency==='JPY'&&row.period==='additional_2026');
  check('V2 additional period displays its actual small episode count',(await page.locator('#v2-currency-detail .v2-metric-grid strong').first().innerText())===String(additional.unique_episodes)&&await page.locator('#v2-currency-detail svg').count()===0);
  await page.locator('#v2-period').selectOption('retrospective');
  const originalConvex=await page.locator('#v2-convex-contrast').innerText();
  await page.locator('#v2-convex-metric').selectOption('mean_cost');
  const actualCost=research.convex.data.contrasts.find(row=>row.scenario==='matched_heston'&&row.metric==='mean_cost');
  check('V2 convex cost selector exposes the actual cost tradeoff',(await page.locator('#v2-convex-contrast').innerText())!==originalConvex&&(await page.locator('#v2-convex-contrast svg title').textContent()).includes(String(actualCost.difference)));
  check('V2 optimization audit preserves small nonzero residuals',(await page.locator('#v2-convex').innerText()).includes(research.convex.data.audit.max_constraint_violation.toExponential(2)));
  await page.locator('#v2-convex-scenario').selectOption('shifted_heston');
  check('V2 convex distribution selector retains actual comparisons',await page.locator('#v2-convex-contrast svg').count()===1);
  await page.locator('#v2-convex-scenario').selectOption('matched_heston');await page.locator('#v2-convex-metric').selectOption('es90');
  check('Every visible V2 input and selector has a label',await page.locator('#research-v2 input:visible,#research-v2 select:visible').evaluateAll(nodes=>nodes.every(node=>node.labels?.length>0)));
  check('V2 publication routes contain all verified official venues',await page.locator('.v2-route').count()===research.publication_routes.data.venues.length);
  await page.locator('#v2-route-filter').selectOption('open');
  check('Open-route filter selects actual available submission paths',await page.locator('.v2-route').count()===3);
  await page.locator('#v2-route-filter').selectOption('later');
  check('Closed and unmet-condition routes remain available separately',await page.locator('.v2-route').count()===3&&(await page.locator('#v2-routes').innerText()).includes('SIAM Undergraduate Research Online'));
  await page.locator('#v2-route-filter').selectOption('all');
  check('Publication status explicitly distinguishes non-proceedings routes',(await page.locator('#v2-routes').innerText()).includes('均不进入会议论文集'));
  const v2DownloadPromise=page.waitForEvent('download');await page.locator('#download-v2').click();const v2Download=await v2DownloadPromise;
  check('V2 actual evidence can be exported',v2Download.suggestedFilename()==='finmath-risklab-v2-evidence.json');await v2Download.saveAs(path.join(output,'v2-evidence-download.json'));
  await page.locator('#toast').waitFor({state:'hidden'});
  await page.screenshot({path:path.join(output,'06-research-v2-desktop.png'),fullPage:true});
  for(const section of ['v2-primary','v2-convex','v2-routes'])await page.locator(`#${section}`).screenshot({path:path.join(output,`${section}-desktop.png`)});
  const missingReply={...research,historical:{status:'missing',message:'Test-controlled missing historical result'},selection:{status:'invalid',message:'Test-controlled invalid selection result'},convex:{status:'too_large',message:'Test-controlled oversized result'}};
  await page.route('**/api/research-v2',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(missingReply)}));
  await page.locator('#refresh-v2').click();await page.waitForFunction(()=>document.querySelector('#v2-primary').innerText.includes('Test-controlled missing historical result'));
  check('V2 missing and invalid files produce explicit nonnumeric states',(await page.locator('#v2-primary').innerText()).includes('文件无效')&&(await page.locator('#v2-convex').innerText()).includes('超过读取上限'));
  await page.unroute('**/api/research-v2');await page.locator('#refresh-v2').click();
  await page.waitForFunction(()=>!document.querySelector('#refresh-v2').disabled);
  await page.setViewportSize({width:390,height:844});
  for(const name of ['overview','pricing','hedging','historical','competencies','research-v2']){
    await page.locator(`nav a[data-page="${name}"]`).click();
    check(`Mobile ${name} has no horizontal page overflow`,await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
    await page.screenshot({path:path.join(output,`mobile-${name}.png`),fullPage:name!=='hedging'});
    if(name==='research-v2')await page.locator('#v2-convex').screenshot({path:path.join(output,'v2-convex-mobile.png')});
  }
  await page.locator('nav a[data-page="pricing"]').click();await page.locator('#price-form input[name="vol"]').fill('0.3');response=page.waitForResponse(r=>r.url().endsWith('/api/price')&&r.request().method()==='POST');await page.locator('#price-form button[type="submit"]').click();result=await(await response).json();check('Mobile form completes live calculation',result.parameters.vol===.3);
  await page.waitForFunction(()=>document.querySelector('#price-message').classList.contains('success'));
  await page.route('**/api/price',async route=>{await new Promise(resolve=>setTimeout(resolve,250));await route.fulfill({status:422,contentType:'application/json',body:JSON.stringify({error:'Test-controlled numerical domain failure'})});});
  await page.locator('#price-form button[type="submit"]').click();
  check('Loading disables submit to prevent duplicate work',await page.locator('#price-form button[type="submit"]').isDisabled());
  await page.waitForFunction(()=>document.querySelector('#price-message').classList.contains('error'));
  check('Server errors are visible without fabricated replacement',(await page.locator('#price-message').innerText()).includes('Test-controlled numerical domain failure'));
  await page.unroute('**/api/price');
  check('Every visible control has an accessible label',await page.locator('input:visible,select:visible').evaluateAll(nodes=>nodes.every(node=>node.labels?.length>0)));
  check('No uncaught browser JavaScript errors',browserErrors.length===0);
  fs.writeFileSync(path.join(output,'browser_validation.json'),JSON.stringify({status:'passed',engine:'Microsoft Edge via Playwright',viewport_desktop:[1440,1100],viewport_mobile:[390,844],checks,check_count:checks.length,browser_errors:browserErrors,console_messages:consoleErrors,expected_error_probe:'The script intentionally intercepts one price request with HTTP 422 to verify visible failure and preserved prior output. This HTTP console error is expected; successful calculation paths had no console errors.',note:'Checks assert numerical behavior and browser interaction; screenshots require separate visual review. Not a WCAG certification or user study.'},null,2));
  console.log(JSON.stringify({status:'passed',checks:checks.length,output,browserErrors,consoleErrors}));
 }finally{await browser.close();}
}
main().catch(error=>{fs.writeFileSync(path.join(output,'browser_failure.json'),JSON.stringify({status:'failed',checks,error:String(error),browserErrors,consoleErrors},null,2));console.error(error);process.exitCode=1;});
